version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_DATABASE=dbas_mds
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - dbasNet

  appservice:
    build: ./DBAS
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dbas_mds
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8080:8080
    networks:
      - dbasNet

networks:
  dbasNet:
